# Generated by Django 4.2.2 on 2023-08-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('ean_num', models.CharField(blank=True, max_length=100, null=True)),
                ('mpn_num', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('season', models.CharField(max_length=100)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('load_index', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('speed_index', models.CharField(max_length=100)),
                ('rim_protection', models.BooleanField()),
                ('run_flat', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Tyre',
                'verbose_name_plural': 'Tyres',
            },
        ),
    ]
