# Generated by Django 4.2.3 on 2023-07-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('ean_num', models.CharField(max_length=100)),
                ('mpn_num', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('diameter', models.IntegerField()),
                ('load_index', models.IntegerField()),
                ('speed_index', models.CharField(max_length=100)),
                ('rim_protection', models.BooleanField()),
                ('run_flat', models.BooleanField()),
                ('season', models.CharField(max_length=100)),
            ],
        ),
    ]
