# Generated by Django 4.2.3 on 2023-07-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarParts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tires',
            name='size',
        ),
        migrations.AlterField(
            model_name='tires',
            name='ean_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tires',
            name='mpn_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tires',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tires',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
