# Generated by Django 4.2.5 on 2023-10-07 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, null=True),
        ),
    ]
